### ISSUE TITLE
A problem for this code

### ISSUE THREAD

**Issue by sjm1992st** [StevenReitsma/genops#1]
Hi, I run your code ,it has some error,like:
D:\anaconda2\python.exe E:/pythonworkspace/Modelfitting/algorithm.py
WARNING (theano.gof.compilelock): Overriding existing lock by dead process '12280' (I am process '12772')
DEBUG: nvcc STDOUT mod.cu
   ���ڴ����� C:/Users/user/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpwwst6o/265abc51f7c376c224983485238ff1a5.lib �Ͷ��� C:/Users/user/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpwwst6o/265abc51f7c376c224983485238ff1a5.exp

Using gpu device 0: GeForce GTX 750 Ti (CNMeM is enabled with initial size: 80.0% of memory, cuDNN 5103)
D:\anaconda2\lib\site-packages\theano\sandbox\cuda\__init__.py:600: UserWarning: Your cuDNN version is more recent than the one Theano officially supports. If you see any problems, try updating Theano or downgrading cuDNN to version 5.
  warnings.warn(warn)
D:\anaconda2\lib\site-packages\mpltools\style\__init__.py:42: FutureWarning: 

    The style-sheet functionality in mpltools has been integrated into
    Matplotlib >= 1.4. This module will be removed in a future release.

    Note that style-sheets used by `matplotlib.style` use the standard
    Matplotlib rc-file syntax instead of the INI format used by `mpltools`.
    This mostly means un-quoting strings and changing '=' to ':'.

  """, FutureWarning)
D:\anaconda2\lib\site-packages\matplotlib\__init__.py:872: UserWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.
  warnings.warn(self.msg_depr % (key, alt_key))
15:25:36: Compiling...
15:25:39: Compilation successfully completed.
15:25:39: Running algorithm...
Traceback (most recent call last):
  File "E:/pythonworkspace/Modelfitting/algorithm.py", line 273, in <module>
    entities, start, end, iterations,f = ea.run(generations = 150)
  File "E:/pythonworkspace/Modelfitting/algorithm.py", line 230, in run
    crossover()
  File "D:\anaconda2\lib\site-packages\theano\compile\function_module.py", line 871, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "D:\anaconda2\lib\site-packages\theano\gof\link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "D:\anaconda2\lib\site-packages\theano\compile\function_module.py", line 859, in __call__
    outputs = self.fn()
RuntimeError: Failed to initialize curand generator
Apply node that caused the error: CURAND_Uniform{inplace=True, out_dtype=CudaNdarrayType(float32, vector)}(<Generic>, Elemwise{Cast{int32}}.0)
Toposort index: 14
Inputs types: [<theano.gof.type.Generic object at 0x0000000003159400>, TensorType(int32, vector)]
Inputs shapes: ['No shapes', (1L,)]
Inputs strides: ['No strides', (4L,)]
Inputs values: [False, array([500])]
Outputs clients: [['output'], [HostFromGpu(CURAND_Uniform{inplace=True, out_dtype=CudaNdarrayType(float32, vector)}.1)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuModuleUnload failed: unspecified launch failure

could you help me solve it? THX

**Comment by StevenReitsma** [comment]
Hey, this is a very old project so I'm not really sure of how everything works exactly anymore.. but it looks like there is some error in initializing curand. I would recommend reinstalling the newest version of CUDA to see whether that has any effect.

**Comment by sjm1992st** [comment]
I think the problem is happened in theano,so i want know what's your version you use?
